"""add recovery scores table

Revision ID: 0eabf68d8f58
Revises: d529dc851b75
Create Date: 2026-06-01 11:22:06.615918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eabf68d8f58'
down_revision: Union[str, None] = 'd529dc851b75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hrv_rmssd', sa.Float(), nullable=True),
    sa.Column('hrv_trend', sa.Float(), nullable=True),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('subjective_feeling', sa.Integer(), nullable=True),
    sa.Column('soreness', sa.Integer(), nullable=True),
    sa.Column('readiness_score', sa.Float(), nullable=True),
    sa.Column('readiness_zone', sa.String(length=20), nullable=True),
    sa.Column('resting_hr', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_scores_date'), 'recovery_scores', ['date'], unique=False)
    op.create_index(op.f('ix_recovery_scores_id'), 'recovery_scores', ['id'], unique=False)
    op.create_index(op.f('ix_recovery_scores_user_id'), 'recovery_scores', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_scores_user_id'), table_name='recovery_scores')
    op.drop_index(op.f('ix_recovery_scores_id'), table_name='recovery_scores')
    op.drop_index(op.f('ix_recovery_scores_date'), table_name='recovery_scores')
    op.drop_table('recovery_scores')
    # ### end Alembic commands ###
