"""initial models

Revision ID: 2979d88ece68
Revises: 
Create Date: 2026-05-30 14:02:57.900010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2979d88ece68'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('strava_athlete_id', sa.Integer(), nullable=True),
    sa.Column('strava_access_token', sa.String(length=255), nullable=True),
    sa.Column('strava_refresh_token', sa.String(length=255), nullable=True),
    sa.Column('strava_token_expires_at', sa.Integer(), nullable=True),
    sa.Column('ftp', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('resting_hr', sa.Integer(), nullable=True),
    sa.Column('max_hr', sa.Integer(), nullable=True),
    sa.Column('training_goal', sa.Enum('BASE', 'BUILD', 'PEAK', 'RACE', 'RECOVERY', name='traininggoal'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('strava_athlete_id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('strava_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('strava_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('elapsed_time', sa.Integer(), nullable=True),
    sa.Column('moving_time', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('total_elevation_gain', sa.Float(), nullable=True),
    sa.Column('average_watts', sa.Float(), nullable=True),
    sa.Column('max_watts', sa.Float(), nullable=True),
    sa.Column('weighted_average_watts', sa.Float(), nullable=True),
    sa.Column('average_heartrate', sa.Float(), nullable=True),
    sa.Column('max_heartrate', sa.Float(), nullable=True),
    sa.Column('average_cadence', sa.Float(), nullable=True),
    sa.Column('perceived_exertion', sa.Integer(), nullable=True),
    sa.Column('kilojoules', sa.Float(), nullable=True),
    sa.Column('suffer_score', sa.Integer(), nullable=True),
    sa.Column('training_load', sa.Float(), nullable=True),
    sa.Column('workout_type', sa.Enum('ENDURANCE', 'TEMPO', 'THRESHOLD', 'VO2MAX', 'SPRINT', 'RECOVERY', 'INTERVAL', 'CUSTOM', name='workouttype'), nullable=True),
    sa.Column('intensity_factor', sa.Float(), nullable=True),
    sa.Column('training_stress_score', sa.Float(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strava_id')
    )
    op.create_index(op.f('ix_strava_activities_id'), 'strava_activities', ['id'], unique=False)
    op.create_index(op.f('ix_strava_activities_user_id'), 'strava_activities', ['user_id'], unique=False)
    op.create_table('training_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ctl', sa.Float(), nullable=True),
    sa.Column('atl', sa.Float(), nullable=True),
    sa.Column('tsb', sa.Float(), nullable=True),
    sa.Column('total_tss', sa.Float(), nullable=True),
    sa.Column('total_duration_minutes', sa.Float(), nullable=True),
    sa.Column('total_distance_km', sa.Float(), nullable=True),
    sa.Column('total_kj', sa.Float(), nullable=True),
    sa.Column('ride_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_metrics_date'), 'training_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_training_metrics_id'), 'training_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_training_metrics_user_id'), 'training_metrics', ['user_id'], unique=False)
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('scheduled_time', sa.String(length=10), nullable=True),
    sa.Column('workout_type', sa.Enum('ENDURANCE', 'TEMPO', 'THRESHOLD', 'VO2MAX', 'SPRINT', 'RECOVERY', 'INTERVAL', 'CUSTOM', name='workouttype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('target_power_zone', sa.String(length=50), nullable=True),
    sa.Column('target_hr_zone', sa.String(length=50), nullable=True),
    sa.Column('target_rpe', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('SUGGESTED', 'ACCEPTED', 'COMPLETED', 'SKIPPED', name='workoutstatus'), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('actual_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('actual_distance_km', sa.Float(), nullable=True),
    sa.Column('actual_tss', sa.Float(), nullable=True),
    sa.Column('actual_kj', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('strava_activity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['strava_activity_id'], ['strava_activities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workouts_id'), 'workouts', ['id'], unique=False)
    op.create_index(op.f('ix_workouts_scheduled_date'), 'workouts', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_workouts_user_id'), 'workouts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workouts_user_id'), table_name='workouts')
    op.drop_index(op.f('ix_workouts_scheduled_date'), table_name='workouts')
    op.drop_index(op.f('ix_workouts_id'), table_name='workouts')
    op.drop_table('workouts')
    op.drop_index(op.f('ix_training_metrics_user_id'), table_name='training_metrics')
    op.drop_index(op.f('ix_training_metrics_id'), table_name='training_metrics')
    op.drop_index(op.f('ix_training_metrics_date'), table_name='training_metrics')
    op.drop_table('training_metrics')
    op.drop_index(op.f('ix_strava_activities_user_id'), table_name='strava_activities')
    op.drop_index(op.f('ix_strava_activities_id'), table_name='strava_activities')
    op.drop_table('strava_activities')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
