"""add_weather_fields

Revision ID: d529dc851b75
Revises: 2979d88ece68
Create Date: 2026-05-31 21:20:53.466250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd529dc851b75'
down_revision: Union[str, None] = '2979d88ece68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location_lat', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('location_lon', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('weather_preference', sa.String(length=20), nullable=True))
    op.add_column('workouts', sa.Column('is_indoor', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts', 'is_indoor')
    op.drop_column('users', 'weather_preference')
    op.drop_column('users', 'location_lon')
    op.drop_column('users', 'location_lat')
    # ### end Alembic commands ###
