"""add encrypted api key columns to user

Revision ID: f766245dd987
Revises: 0eabf68d8f58
Create Date: 2026-06-02 19:41:14.779482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f766245dd987'
down_revision: Union[str, None] = '0eabf68d8f58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('intervals_api_key_encrypted', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('intervals_athlete_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'intervals_athlete_id')
    op.drop_column('users', 'intervals_api_key_encrypted')
    # ### end Alembic commands ###
